version: "3"

services:
  # Flask app Container
  flask: 
    container_name: "flask_app"
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      - mysql 

  # MySQL DB Container
  mysql: 
    image: mysql:8.0.30
    container_name: "flask_mysql"
    ports:
      - "3306:3306"
    volumes:
      - ./docker:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: myjobhist
      MYSQL_USER: sa
      MYSQL_PASSWORD: admin
  

