version: "3"

services:
  app: # Set Flask app Container
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    restart: always
    container_name: flask_app_with_docker
    depends_on:
      - mysql 

  mysql: # Set MySQL DB Container
    image: mysql:8.0.30
    volumes:
      - ./docker/data:/var/lib/mysql
      - ./docker/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: myjobhist
      MYSQL_USER: sa
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    restart: always
    container_name: mysql_flask